---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: sample-rest-service
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: sample-rest-service
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: sample-rest-service
      spec:
        containers:
          - name: sample-rest-service
            image: ${IMAGE_REGISTRY_URL}/${IMAGE_NAMESPACE}/sample-rest-service:${IMAGE_TAG}
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
parameters:
  - name: IMAGE_NAMESPACE
    displayName: Image Repository Name
    description: The Repository name for image
    required: true
  - name: IMAGE_TAG
    displayName: Image tag
    description: Image tag
    required: true
  - name: IMAGE_REGISTRY_URL
    displayName: Registry URL
    description: Registry URL
    required: true

