---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: sample-rest-service
    labels:
      external: sample-rest-service
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      name: sample-rest-service
    type: ClusterIP
    sessionAffinity: None
