---
ansible_host: localhost
ansible_connection: local

project_params:
  NAMESPACE: "{{ namespace }}"
  IMAGE_NAMESPACE: "{{ image_namespace }}"
  IMAGE_REGISTRY_URL: "{{ image_registry_url }}"
  IMAGE_TAG: "{{ image_tag if image_tag is defined else 'latest' }}"

route_params:
  SUBDOMAIN: "{{ subdomain if subdomain is defined else omit }}"

openshift_cluster_content:
  - object: Create Application Resources
    content:
      - name: Build Config
        template: "{{ playbook_dir }}/buildConfig.yml"
        params_from_vars: "{{ project_params }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - create-build-config
      - name: Deployment Config
        template: "{{ playbook_dir }}/deploymentConfig.yml"
        params_from_vars: "{{ project_params }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - deploy
      - name: Service
        template: "{{ playbook_dir }}/service.yml"
        params_from_vars: "{{ project_params }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - deploy
      - name: Route
        template: "{{ playbook_dir }}/route.yml"
        namespace: "{{ project_params.NAMESPACE }}"
        params_from_vars: "{{ project_params | combine(route_params) }}"
        tags:
          - deploy
